apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: cloudshop-prod
type: Opaque
data:
  # Base64 encoded values
  # Utilisez : echo -n 'valeur' | base64
  POSTGRES_USER: YWRtaW4=           # admin
  POSTGRES_PASSWORD: cGFzc3dvcmQxMjM=   # password123
  POSTGRES_DB: Y2xvdWRzaG9w           # cloudshop
